### ISSUE TITLE
npm runkit example broken

### ISSUE THREAD

**Issue by dhowe** [isaaclyman/muzak-js#2]
![screen shot 2018-12-30 at 12 28 53 am](https://user-images.githubusercontent.com/737638/50540282-ee8c1280-0bc9-11e9-9128-87fa5b4307b1.png)

**Comment by isaaclyman** [comment]
RunKit isn't supported and never will be. Since it doesn't run in a browser environment, the Web Audio API isn't available. blackswan-js would be useless in node.

**Comment by dhowe** [comment]
understood -- maybe an error message saying this?
